routes/web.php
<?php

use App\Http\Controllers\PostController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
  return redirect()->route('posts.index');
});

Route::get('/posts/user/{user}', [PostController::class, 'userPosts'])
  ->name('posts.user');

Route::post('/posts/{post}/like', [PostController::class, 'like'])
  ->name('posts.like');

Route::resource('posts', PostController::class);

Route::resource('users', UserController::class)->only(['show', 'edit', 'update']);

Auth::routes();

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
  use HasFactory, Notifiable;

  /**
   * The attributes that are mass assignable.
   *
   * @var array
   */
  protected $fillable = [
    'first_name',
    'last_name',
    'phone',
    'photo',
    'email',
    'password',
  ];

  /**
   * The attributes that should be hidden for arrays.
   *
   * @var array
   */
  protected $hidden = [
    'password',
    'remember_token',
  ];

  /**
   * The attributes that should be cast to native types.
   *
   * @var array
   */
  protected $casts = [
    'email_verified_at' => 'datetime',
  ];

  /**
   * Relation to posts.
   *
   * @return \Illuminate\Database\Eloquent\Relations\HasMany
   */
  public function posts() {

    return $this->hasMany(Post::class);
  }

  /**
   * Relation to likes.
   *
   * @return \Illuminate\Database\Eloquent\Relations\HasMany
   */
  public function likes() {

    return $this->hasMany(Like::class);
  }

  /**
   * Relation to likes through posts.
   * (get all likes that user's posts received)
   *
   * @return \Illuminate\Database\Eloquent\Relations\HasManyThrough
   */
  public function likesGained() {

    return $this->hasManyThrough(Like::class, Post::class)
      ->where('likes.operation', Like::LIKE);
  }

  /**
   * Relation to dislikes through posts.
   * (get all dislikes that user's posts received)
   *
   * @return \Illuminate\Database\Eloquent\Relations\HasManyThrough
   */
  public function dislikesGained() {

    return $this->hasManyThrough(Like::class, Post::class)
      ->where('likes.operation', Like::DISLIKE);
  }

  /**
   * Getter for user's full name.
   *
   * @return string
   */
  public function getNameAttribute() {

    return $this->last_name . ', ' . $this->first_name;
  }

  /**
   * Get profile photo url.
   *
   * @return string
   */
  public function getPhotoUrlAttribute() {

    return !empty($this->photo) ? asset($this->photo) : asset('img/user-default.jpg');
  }

  /**
   * Get total likes received by user.
   *
   * @return int
   */
  public function getTotalLikesAttribute() {

    return $this->likesGained()->count();
  }

  /**
   * Get total dislikes received by user.
   *
   * @return int
   */
  public function getTotalDislikesAttribute() {

    return $this->dislikesGained()->count();
  }
}

resources/views/header.blade.php
<header class="masthead" style="background-image: url('{{ asset('img/home-bg.jpg') }}')">
  <div class="overlay"></div>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <div class="site-heading">
          <h1>@yield('title')</h1>
          <span class="subheading">{{ $subtitle ?? '' }}</span>
        </div>
      </div>
    </div>
  </div>
</header>

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{ __('You are logged in!') }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layout.blade.php
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <!-- CSRF Token -->
  <meta name="csrf-token" content="{{ csrf_token() }}">

  <title>{{ config('app.name', 'Laravel') }}</title>

  <!-- Bootstrap core CSS -->
  <link rel="stylesheet" href="{{ mix('/css/app.css') }}"/>

  <!-- Custom fonts for this template -->
  <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet'
        type='text/css'>
  <link
      href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800'
      rel='stylesheet' type='text/css'>

</head>

<body>
<div id="app">

  <!-- Navigation -->
  @include('nav')

  <!-- Page Header -->
  @include('header')

  <!-- Display notifications -->
  @include ('flash::message')

  <!-- Main Content -->
  <div class="container">
    {!! $breadcrumbs ?? '' !!}
    @yield('content')
  </div>

<!-- Footer -->
  <footer>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <ul class="list-inline text-center">
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
          </ul>
          <p class="copyright text-muted">Copyright &copy; Poster 2021</p>
        </div>
      </div>
    </div>
  </footer>

</div>
</body>

<script src="{{ mix('/js/app.js') }}" type="text/javascript"></script>
<script src="{{ mix('/js/clean-blog.min.js') }}" type="text/javascript"></script>

</html>

resources/views/nav.blade.php
<nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
  <div class="container">
    <a class="navbar-brand" href="{{ route('posts.index') }}">{{ config('app.name') }}</a>
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
            data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false"
            aria-label="Toggle navigation">
      Menu
      <i class="fas fa-bars"></i>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        @guest
          @if (Route::has('login'))
            <li class="nav-item ml-5">
              <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
            </li>
          @endif

          @if (Route::has('register'))
            <li class="nav-item">
              <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
            </li>
          @endif
        @else
          <li class="nav-item">
            <a class="nav-link" href="{{ route('posts.user', ['user' => auth()->user()]) }}">My feed</a>
          </li>

          <li class="nav-item dropdown ml-5">
            <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown"
               aria-haspopup="true" aria-expanded="false" v-pre>
              {{ Auth::user()->name }}
            </a>

            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{{ route('users.show', ['user' => auth()->user()]) }}">
                {{ __('View profile') }}
              </a>
              <a class="dropdown-item" href="{{ route('users.edit', ['user' => auth()->user()]) }}">
                {{ __('Edit profile') }}
              </a>
              <a class="dropdown-item" href="{{ route('logout') }}"
                 onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                {{ __('Logout') }}
              </a>

              <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                @csrf
              </form>
            </div>
          </li>

          <li class="nav-item">
            <img class="profile-photo float-right" src="{{ auth()->user()->photo_url }}" width="50" height="50">
          </li>
        @endguest
      </ul>
    </div>
  </div>
</nav>