routes/web.php
<?php

use App\Http\Controllers\PostController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
  return redirect()->route('posts.index');
});

Route::get('/posts/user/{user}', [PostController::class, 'userPosts'])
  ->name('posts.user');

Route::post('/posts/{post}/like', [PostController::class, 'like'])
  ->name('posts.like');

Route::resource('posts', PostController::class);

Route::resource('users', UserController::class)->only(['show', 'edit', 'update']);

Auth::routes();

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
  use HasFactory, Notifiable;

  /**
   * The attributes that are mass assignable.
   *
   * @var array
   */
  protected $fillable = [
    'first_name',
    'last_name',
    'phone',
    'photo',
    'email',
    'password',
  ];

  /**
   * The attributes that should be hidden for arrays.
   *
   * @var array
   */
  protected $hidden = [
    'password',
    'remember_token',
  ];

  /**
   * The attributes that should be cast to native types.
   *
   * @var array
   */
  protected $casts = [
    'email_verified_at' => 'datetime',
  ];

  /**
   * Relation to posts.
   *
   * @return \Illuminate\Database\Eloquent\Relations\HasMany
   */
  public function posts() {

    return $this->hasMany(Post::class);
  }

  /**
   * Relation to likes.
   *
   * @return \Illuminate\Database\Eloquent\Relations\HasMany
   */
  public function likes() {

    return $this->hasMany(Like::class);
  }

  /**
   * Relation to likes through posts.
   * (get all likes that user's posts received)
   *
   * @return \Illuminate\Database\Eloquent\Relations\HasManyThrough
   */
  public function likesGained() {

    return $this->hasManyThrough(Like::class, Post::class)
      ->where('likes.operation', Like::LIKE);
  }

  /**
   * Relation to dislikes through posts.
   * (get all dislikes that user's posts received)
   *
   * @return \Illuminate\Database\Eloquent\Relations\HasManyThrough
   */
  public function dislikesGained() {

    return $this->hasManyThrough(Like::class, Post::class)
      ->where('likes.operation', Like::DISLIKE);
  }

  /**
   * Getter for user's full name.
   *
   * @return string
   */
  public function getNameAttribute() {

    return $this->last_name . ', ' . $this->first_name;
  }

  /**
   * Get profile photo url.
   *
   * @return string
   */
  public function getPhotoUrlAttribute() {

    return !empty($this->photo) ? asset($this->photo) : asset('img/user-default.jpg');
  }

  /**
   * Get total likes received by user.
   *
   * @return int
   */
  public function getTotalLikesAttribute() {

    return $this->likesGained()->count();
  }

  /**
   * Get total dislikes received by user.
   *
   * @return int
   */
  public function getTotalDislikesAttribute() {

    return $this->dislikesGained()->count();
  }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Illuminate\Validation\ValidationException;
use Laracasts\Flash\Flash;

class UserController extends Controller
{
  /**
   * Display the specified resource.
   *
   * @param \App\Models\User $user
   * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\Response
   */
  public function show(User $user) {

    $this->authorize('view', $user);

    return view('users.show', compact('user'));
  }

  /**
   * Show the form for editing the specified resource.
   *
   * @param \App\Models\User $user
   * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\Response
   */
  public function edit(User $user) {

    $this->authorize('update', $user);

    return view('users.edit', compact('user'));
  }

  /**
   * Update the specified resource in storage.
   *
   * @param \Illuminate\Http\Request $request
   * @param \App\Models\User $user
   *
   * @return \Illuminate\Http\RedirectResponse
   *
   * @throws ValidationException
   */
  public function update(Request $request, User $user) {

    $this->authorize('update', $user);

    $validated = $request->validate([
      'first_name' => 'required|max:255',
      'last_name' => 'required|max:255',
      'phone' => 'nullable|regex:/^\(\d{3}\)\s\d{3}-\d{4}$/', // format (xxx) xxx-xxxx
      'photo' => 'image',
    ], [
      'phone.regex' => 'Phone number has invalid format.'
    ]);

    // Process user photo.
    if ($request->has('photo')) {

      $oldPhoto = $user->photo;

      // Save new photo.
      $validated['photo'] = $validated['photo']->store('avatars');
      if (!$validated['photo']) {
        throw ValidationException::withMessages([
          'photo' => ['Failed to save photo.'],
        ]);
      }

      // Remove old profile photo.
      if (!empty($oldPhoto)) {
        Storage::delete($oldPhoto);
      }
    }

    $user->update($validated);

    Flash()->success('Profile updated.');

    return redirect()->route('posts.index');
  }

}

resources/views/users/edit.blade.php
@extends('layout')

@section('title')
  {{ $title ?? 'Edit profile' }}
@endsection

@section('content')

  <article>
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">

        <form method="POST" action="{{ route('users.update', ['user' => $user]) }}" enctype="multipart/form-data">
          {{ csrf_field() }}
          {{ method_field('PATCH') }}
          <div class="form-group">
            <label for="first_name">{{ __('First Name') }}</label>
            <input id="first_name" type="text" name="first_name" class="form-control"
                   maxlength="255" value="{{ old('first_name') ?? $user->first_name }}" required>
            @error('first_name')
              <small class="text-danger">{{ $message }}</small>
            @enderror
          </div>
          <div class="form-group">
            <label for="last_name">{{ __('Last Name') }}</label>
            <input id="last_name" type="text" name="last_name" class="form-control"
                   maxlength="255" value="{{ old('last_name') ?? $user->last_name }}" required>
            @error('last_name')
              <small class="text-danger">{{ $message }}</small>
            @enderror
          </div>
          <div class="form-group">
            <phone-input input-id="phone"
                         input-name="phone"
                         input-label="{{ __('Phone Number') }}"
                         input-value="{{ old('phone') ?? $user->phone  }}">
            </phone-input>
            @error('phone')
              <small class="text-danger">{{ $message }}</small>
            @enderror
          </div>

          <div class="form-group">
            <label for="photo">{{ __('Photo') }}</label>
            <input id="photo" type="file" class="form-control-file" name="photo">
            @error('photo')
              <small class="text-danger">{{ $message }}</small>
            @enderror
            @if(!empty($user->photo))
              <img class="mt-3" src="{{ $user->photo_url }}" width="100" height="100">
            @endif
            <hr>
          </div>

          <button type="submit" class="btn btn-primary">Update</button>
        </form>

      </div>
    </div>
  </article>

@endsection

resources/views/users/show.blade.php
@extends('layout')

@section('title')
  {{ $title ?? 'Profile of ' . $user->name }}
@endsection

@section('content')

  <div class="container">
    <dl class="row">
      <dt class="offset-2 col-sm-3 text-right"></dt>
      <dd class="col-md-7 mb-5"><img class="profile-photo" src="{{ $user->photo_url }}" width="200" height="200" alt="Profile photo"></dd>
      <dt class="offset-2 col-sm-3 text-right">{{ __('Name') }}</dt>
      <dd class="col-md-7">{{ $user->name }}</dd>
      <dt class="offset-2 col-sm-3 text-right">{{ __('Email') }}</dt>
      <dd class="col-md-7">{{ $user->email }}</dd>
      <dt class="offset-2 col-sm-3 text-right">{{ __('Phone Number') }}</dt>
      <dd class="col-md-7">{{ $user->phone }}</dd>
    </dl>
    <hr>
    <dl class="row">
      <dt class="offset-2 col-sm-3 text-right">{{ __('Likes Gained') }}</dt>
      <dd class="col-md-7">{{ $user->total_likes }}</dd>
      <dt class="offset-2 col-sm-3 text-right">{{ __('Dislikes Gained') }}</dt>
      <dd class="col-md-7">{{ $user->total_dislikes }}</dd>
    </dl>
  </div>

@endsection