routes/web.php
<?php

use App\Http\Controllers\PostController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
  return redirect()->route('posts.index');
});

Route::get('/posts/user/{user}', [PostController::class, 'userPosts'])
  ->name('posts.user');

Route::post('/posts/{post}/like', [PostController::class, 'like'])
  ->name('posts.like');

Route::resource('posts', PostController::class);

Route::resource('users', UserController::class)->only(['show', 'edit', 'update']);

Auth::routes();

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;
use Mews\Purifier\Facades\Purifier;

class Post extends Model
{
  use HasFactory;

  protected $fillable = [
    'title',
    'body',
  ];

  /**
   * Mutator for body field.
   *
   * @param $value
   */
  public function setBodyAttribute($value) {

    // Clean possible html malicious tags.
    $this->attributes['body'] = Purifier::clean($value);
  }

  /**
   * Relation to User model.
   *
   * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
   */
  public function author() {
    return $this->belongsTo(User::class, 'user_id', 'id');
  }

  /**
   * Relation to Like model.
   *
   * @return \Illuminate\Database\Eloquent\Relations\HasMany
   */
  public function likes() {
    return $this->hasMany(Like::class);
  }

  /**
   * Get count of likes for this post.
   *
   * @return int
   */
  public function getLikesCountAttribute() {
    return $this->likes()->where('operation', Like::LIKE)->count();
  }

  /**
   * Get count of dislikes for this post.
   *
   * @return int
   */
  public function getDislikesCountAttribute() {
    return $this->likes()->where('operation', Like::DISLIKE)->count();
  }

  /**
   * Convert full body to teaser.
   *
   * @return string
   */
  public function getTeaserAttribute() {

    return Str::words(strip_tags($this->body), 30, '...');
  }

  /**
   * Determine if provided user liked this post.
   *
   * @param User $user
   *
   * @return bool
   */
  public function likedBy(User $user): bool {

    if (empty($user)) {
      return false;
    }

    return $this->likes()
      ->where('user_id', $user->id)
      ->where('operation', Like::LIKE)
      ->exists();
  }

  /**
   * Determine if provided user disliked this post.
   *
   * @param User $user
   *
   * @return bool
   */
  public function dislikedBy(User $user): bool {

    if (empty($user)) {
      return false;
    }

    return $this->likes()
      ->where('user_id', $user->id)
      ->where('operation', Like::DISLIKE)
      ->exists();
  }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
  use HasFactory, Notifiable;

  /**
   * The attributes that are mass assignable.
   *
   * @var array
   */
  protected $fillable = [
    'first_name',
    'last_name',
    'phone',
    'photo',
    'email',
    'password',
  ];

  /**
   * The attributes that should be hidden for arrays.
   *
   * @var array
   */
  protected $hidden = [
    'password',
    'remember_token',
  ];

  /**
   * The attributes that should be cast to native types.
   *
   * @var array
   */
  protected $casts = [
    'email_verified_at' => 'datetime',
  ];

  /**
   * Relation to posts.
   *
   * @return \Illuminate\Database\Eloquent\Relations\HasMany
   */
  public function posts() {

    return $this->hasMany(Post::class);
  }

  /**
   * Relation to likes.
   *
   * @return \Illuminate\Database\Eloquent\Relations\HasMany
   */
  public function likes() {

    return $this->hasMany(Like::class);
  }

  /**
   * Relation to likes through posts.
   * (get all likes that user's posts received)
   *
   * @return \Illuminate\Database\Eloquent\Relations\HasManyThrough
   */
  public function likesGained() {

    return $this->hasManyThrough(Like::class, Post::class)
      ->where('likes.operation', Like::LIKE);
  }

  /**
   * Relation to dislikes through posts.
   * (get all dislikes that user's posts received)
   *
   * @return \Illuminate\Database\Eloquent\Relations\HasManyThrough
   */
  public function dislikesGained() {

    return $this->hasManyThrough(Like::class, Post::class)
      ->where('likes.operation', Like::DISLIKE);
  }

  /**
   * Getter for user's full name.
   *
   * @return string
   */
  public function getNameAttribute() {

    return $this->last_name . ', ' . $this->first_name;
  }

  /**
   * Get profile photo url.
   *
   * @return string
   */
  public function getPhotoUrlAttribute() {

    return !empty($this->photo) ? asset($this->photo) : asset('img/user-default.jpg');
  }

  /**
   * Get total likes received by user.
   *
   * @return int
   */
  public function getTotalLikesAttribute() {

    return $this->likesGained()->count();
  }

  /**
   * Get total dislikes received by user.
   *
   * @return int
   */
  public function getTotalDislikesAttribute() {

    return $this->dislikesGained()->count();
  }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Models\Like;
use App\Models\Post;
use App\Models\User;
use Illuminate\Http\Request;

class PostController extends Controller
{
  /**
   * Display a listing of the resource.
   *
   * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\Response
   */
  public function index(Request $request) {

    $this->authorize('viewAny', Post::class);

    $query = Post::with(['author', 'likes'])
      ->whereHas('author');

    if (auth()->check() && $request->has('i_like')) {
      $currentUser = auth()->user();
      $query->whereHas('likes', function ($query) use ($currentUser) {
        $query->where('user_id', $currentUser->id)->where('operation', Like::LIKE);
      });
    }

    $posts = $query->orderByDesc('created_at')
      ->simplePaginate(config('poster.page_size'))
      ->appends($request->query());

    return view('posts.index', compact('posts'));
  }

  /**
   * Display a listing of posts for specified user.
   *
   * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\Response
   */
  public function userPosts(Request $request, User $user) {

    $this->authorize('viewAny', Post::class);

    $query = Post::with(['author', 'likes'])
      ->where('user_id', $user->id);

    if ($user->isNot(auth()->user()) && $request->has('i_like')) {
      $currentUser = auth()->user();
      $query->whereHas('likes', function ($query) use ($currentUser) {
        $query->where('user_id', $currentUser->id)->where('operation', Like::LIKE);
      });
    }

    $posts = $query->orderByDesc('created_at')
      ->simplePaginate(config('poster.page_size'))
      ->appends($request->query());

    $title = $user->is(auth()->user())
      ? 'My feed'
      : 'Feed of ' . $user->name;

    return view('posts.index', compact('posts', 'user', 'title'));
  }

  /**
   * Show the form for creating a new resource.
   *
   * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\Response
   */
  public function create() {

    $this->authorize('create', Post::class);

    return view('posts.create');
  }

  /**
   * Store a newly created resource in storage.
   *
   * @param \Illuminate\Http\Request $request
   * @return \Illuminate\Http\RedirectResponse
   */
  public function store(Request $request) {

    $this->authorize('create', Post::class);

    $validated = $request->validate([
      'title' => 'required|max:255',
      'body' => 'required',
    ]);

    $post = new Post($validated);
    auth()->user()->posts()->save($post);

    return redirect()->route('posts.show', compact('post'));
  }

  /**
   * Display the specified resource.
   *
   * @param \App\Models\Post $post
   * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\Response
   */
  public function show(Post $post) {

    $this->authorize('view', $post);

    return view('posts.show', compact('post'));
  }

  /**
   * Show the form for editing the specified resource.
   *
   * @param \App\Models\Post $post
   * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\Response
   */
  public function edit(Post $post) {

    $this->authorize('update', $post);

    $title = 'Edit post \'' . $post->title . '\'';

    return view('posts.edit', compact('post', 'title'));
  }

  /**
   * Update the specified resource in storage.
   *
   * @param \Illuminate\Http\Request $request
   * @param \App\Models\Post $post
   * @return \Illuminate\Http\RedirectResponse
   */
  public function update(Request $request, Post $post) {

    $this->authorize('update', $post);

    $validated = $request->validate([
      'title' => 'required|max:255',
      'body' => 'required',
    ]);

    $post->update($validated);

    return redirect()->route('posts.show', $post);
  }

  /**
   * Remove the specified resource from storage.
   *
   * @param \App\Models\Post $post
   * @return \Illuminate\Http\RedirectResponse
   */
  public function destroy(Post $post) {

    $this->authorize('delete', $post);

    $post->delete();

    return redirect()->route('posts.index');
  }

  /**
   * Like/dislike a post.
   *
   * @param Request $request
   * @param Post $post
   *
   * @return \Illuminate\Http\RedirectResponse
   *
   * @throws \Illuminate\Auth\Access\AuthorizationException
   */
  public function like(Request $request, Post $post) {

    $this->authorize('like', $post);

    $request->validate([
      'operation' => 'required|in:' . implode(',', [Like::LIKE, Like::DISLIKE, Like::NOOP]),
    ], [
      'operation.in' => 'Operation has illegal value.',
    ]);

    Like::like(auth()->user(), $post, $request->post('operation'));

    return redirect()->back();
  }
}

resources/views/posts/create.blade.php
@extends('layout')

@section('title')
  {{ $title ?? 'New post' }}
@endsection

@section('content')

  <article>
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">

        <form method="POST" action="{{ route('posts.store') }}">
          {{ csrf_field() }}
          <div class="form-group">
            <label for="title">Title</label>
            <input id="title" type="text" name="title" class="form-control" placeholder="Post title" maxlength="255"
                   value="{{ old('title') }}">
            @error('title')
              <small class="text-danger">{{ $message }}</small>
            @enderror
          </div>
          <div class="form-group">
            <label for="body">Body</label>
            <textarea id="body" class="form-control tinymce" name="body" rows="15">{{ old('body') }}</textarea>
            @error('body')
              <small class="text-danger">{{ $message }}</small>
            @enderror
          </div>
          <button type="submit" class="btn btn-primary">Submit</button>
        </form>

      </div>
    </div>
  </article>

@endsection

resources/views/posts/edit.blade.php
@extends('layout')

@section('title')
  {{ $title ?? 'Edit post' }}
@endsection

@section('content')

  <article>
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">

        <form method="POST" action="{{ route('posts.update', ['post' => $post]) }}">
          {{ csrf_field() }}
          {{ method_field('PATCH') }}
          <div class="form-group">
            <label for="title">Title</label>
            <input id="title" type="text" name="title" class="form-control" placeholder="Post title"
                   maxlength="255" value="{{ old('title') ?? $post->title }}">
            @error('title')
            <small class="text-danger">{{ $message }}</small>
            @enderror
          </div>
          <div class="form-group">
            <label for="body">Body</label>
            <textarea id="body" class="form-control tinymce" name="body"
                      rows="15">{{ old('body') ?? $post->body }}</textarea>
            @error('body')
            <small class="text-danger">{{ $message }}</small>
            @enderror
          </div>
          <button type="submit" class="btn btn-primary">Submit</button>
          <button type="button" class="btn btn-default float-right" v-b-modal="'confirmation-modal'"><i class="fa fa-fw fa-ban"></i> Cancel</button>
        </form>

      </div>
    </div>
  </article>

  <simple-confirmation-dialog title="Cancel editing"
                              message="Are you sure you want to cancel editing of post?"
                              @confirm="$redirect('{{ route('posts.show', $post) }}')">
  </simple-confirmation-dialog>

@endsection

resources/views/posts/index.blade.php
@extends('layout')

@section('title')
  <div class="container">
    <div class="row">
      @if(Route::current()->getName() === 'posts.user')
        <div class="col-md-3 mb-3 align-self-center">
          <img class="profile-photo" src="{{ $user->photo_url }}" width="120" height="120">
        </div>
        <div class="col-md-9 align-self-center">
          {{ $title ?? 'Recent posts' }}
        </div>
      @else
        <div class="col-12 align-self-center">
          {{ $title ?? 'Recent posts' }}
        </div>
      @endif
    </div>
  </div>
@endsection

@section('content')

  @if(auth()->check())
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto my-2">
        @can('create', \App\Models\Post::class)
          <a class="btn btn-primary" href="{{ route('posts.create') }}">Make a Post</a>
        @endcan
        @if(empty($user) || auth()->user()->isNot($user))
          @if(!empty($i_like_route))
            <a class="btn btn-primary float-right" href="{{ $i_like_route }}">Show posts I liked</a>
          @elseif(!empty($all_posts_route))
            <a class="btn btn-primary float-right" href="{{ $all_posts_route }}">Show all posts</a>
          @endif
        @endif
      </div>
    </div>
  @endif
  <div class="row">
    <div class="col-lg-8 col-md-10 mx-auto">
      @if(!empty($i_like))
        <span class="badge badge-info badge-pill text-white float-right">Liked by me.</span>
      @endif
      @forelse($posts as $post)
        <div class="post-preview">
          <a href="{{ route('posts.show', ['post' => $post]) }}">
            <h2 class="post-title">
              {{ $post->title }}
            </h2>
            <h3 class="post-subtitle">
                {{ $post->teaser }}
            </h3>
          </a>
          <p class="post-meta">Posted by
            <a href="{{ route('posts.user', $post->author->id) }}">
              @if(auth()->check() && $post->author->is(auth()->user()))
                <b>Me</b>
              @else
                {{ $post->author->name }} (<a href="{{ route('users.show', $post->author) }}" target="_blank">view profile</a>)
              @endif
            </a>
            on {{ $post->created_at }}
          </p>
          @can('like', $post)
            <likes-component action="{{ route('posts.like', ['post' => $post]) }}"
                             :likes-count="{{ $post->likes_count }}"
                             :dislikes-count="{{ $post->dislikes_count }}"
                             :liked="{{ $post->dislikedBy(auth()->user()) ? -1 : ($post->likedBy(auth()->user()) ? 1 : 0) }}">
              <div slot="hidden">
                {{csrf_field()}}
              </div>
            </likes-component>
          @else
            <likes-component :view-mode="true"
                             :likes-count="{{ $post->likes_count }}"
                             :dislikes-count="{{ $post->dislikes_count }}">
              <div slot="hidden">
                {{csrf_field()}}
              </div>
            </likes-component>
          @endcan
        </div>
        <hr>
      @empty
        <p class="mt-5"><i>Looks like feed is empty... You are welcome to make a first post!</i></p>
      @endforelse
    <!-- Pager -->
      {{ $posts->links() }}
    </div>
  </div>

@endsection

resources/views/posts/show.blade.php
@extends('layout')

@section('title')
  {{ $title ?? $post->title }}
@endsection

@section('content')

  <article>
    <div class="post-preview">
      <div class="container">
        @can('update', $post)
          <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto mb-3">
              <a class="btn btn-primary btn-sm float-left" href="{{ route('posts.edit', ['post' => $post]) }}">Edit</a>
              @can('delete', $post)
                <a class="btn btn-danger btn-sm float-right" v-b-modal="'delete-post-modal'">Delete</a>
              @endcan
            </div>
          </div>
        @endcan
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            {!! $post->body !!}
          </div>
        </div>
        <div class="row mt-3">
          <div class="col-lg-8 col-md-10 mx-auto">
            <p class="post-meta">Posted by
              <a href="{{ route('posts.user', $post->author) }}">
                @if(auth()->check() && $post->author->is(auth()->user()))
                  <b>Me</b>
                @else
                  {{ $post->author->name }} (<a href="{{ route('users.show', $post->author) }}" target="_blank">view profile</a>)
                @endif
              </a>
              on {{ $post->created_at }}</p>
          </div>
        </div>
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            @can('like', $post)
              <likes-component action="{{ route('posts.like', ['post' => $post]) }}"
                               :likes-count="{{ $post->likes_count }}"
                               :dislikes-count="{{ $post->dislikes_count }}"
                               :liked="{{ $post->dislikedBy(auth()->user()) ? -1 : ($post->likedBy(auth()->user()) ? 1 : 0) }}">
                <div slot="hidden">
                  {{csrf_field()}}
                </div>
              </likes-component>
            @else
              <likes-component :view-mode="true"
                               :likes-count="{{ $post->likes_count }}"
                               :dislikes-count="{{ $post->dislikes_count }}">
              </likes-component>
            @endcan
          </div>
        </div>
      </div>
    </div>
  </article>

  @can('delete', $post)
    <delete-post-confirmation action="{{ route('posts.destroy', ['post' => $post]) }}"
                              post-title="{{ $post->title }}">
      <div slot="hidden">
        {{ csrf_field() }}
        {{ method_field('DELETE') }}
      </div>
    </delete-post-confirmation>
  @endcan

@endsection